spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/webtest?serverTimezone=UTC&characterEncoding=utf-8
    #username: root
    #password:
    url: jdbc:mysql://10.10.7.53:3306/escp?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: escpmid@sit
    #connection-test-query: SELECT NOW() FROM student
  jpa:
    hibernate:
      ddl-auto: update # 없으면 만들어버린다. (table을 바로 수정해버린다.)
      #ddl-auto: validate # 없으면 에러를 만든다. (수정을 하지는 않음)
    show-sql: true

  redis:
    #host: localhost
    host: 10.10.7.53
    # redis-cli -h 10.10.7.53 -p 6379
    port: 6379

  session:
    store-type: redis
    redis:
      flush-mode: on_save